### ISSUE TITLE
Need update to SMAPI 3.12

### ISSUE THREAD

**Issue by UlyanaLeyana** [Platonymous/PlatoTK#1]
[SMAPI]       - PlatoTK 1.9.3 because initialization failed:
System.Reflection.ReflectionTypeLoadException: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at System.Reflection.RuntimeModule.GetTypes(RuntimeModule module)
   at System.Reflection.RuntimeAssembly.get_DefinedTypes()
   at StardewModdingAPI.Framework.SCore.TryLoadModEntry(Assembly modAssembly, Mod& mod, String& error) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1818
   at StardewModdingAPI.Framework.SCore.TryLoadMod(IModMetadata mod, IModMetadata[] mods, AssemblyLoader assemblyLoader, InterfaceProxyFactory proxyFactory, JsonHelper jsonHelper, ContentCoordinator contentCore, ModDatabase modDatabase, HashSet`1 suppressUpdateChecks, Nullable`1& failReason, String& errorReasonPhrase, String& errorDetails) in C:\source\_Stardew\SMAPI\src\SMAPI\Framework\SCore.cs:line 1744
Failed loading type 'PlatoTK.Patching.HarmonyHelper': System.TypeLoadException: Method 'get_HarmonyInstance' in type 'PlatoTK.Patching.HarmonyHelper' from assembly 'PlatoTK, Version=1.9.3.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.

**Comment by Pathoschild** [comment]
This will be fixed via PR #2.
